// Environment configuration
// Values are read from .env file (EXPO_PUBLIC_ prefix required)
// Restart the dev server after changing .env values

export const ENV = {
    API_BASE_URL: process.env.EXPO_PUBLIC_API_URL || 'https://filmy-backend.onrender.com/api/v1',
    DEV_AUTH_TOKEN: process.env.EXPO_PUBLIC_DEV_TOKEN || "eyJhbGciOiJIUzI1NiIsImtpZCI6IldadEJnODcycFR6dElDcXAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2lkYnh0aHluaXNnd2dua2Rza2dhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI0NTJjMmI0Yy00OTNkLTRmYzItODgxMy0yNWEwMjZjODk3NDciLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY4NjY0NTA4LCJpYXQiOjE3NjgwNTk3MDgsImVtYWlsIjoiIiwicGhvbmUiOiI5MTkxODI3MjA1OTMiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJwaG9uZSIsInByb3ZpZGVycyI6WyJwaG9uZSJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNDUyYzJiNGMtNDkzZC00ZmMyLTg4MTMtMjVhMDI2Yzg5NzQ3In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib3RwIiwidGltZXN0YW1wIjoxNzY4MDU5NzA4fV0sInNlc3Npb25faWQiOiJlODNjZGFjMC05ZTE4LTQyMTQtOGIyZi00MDZlMzIzODM5ZTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.xK6Y0WzSquVfkIzHyqJdGYPXB7nDJZXcG6i6iGWFjFE",
    IS_DEV: __DEV__,
} as const;
