// Environment configuration
// Values are read from .env file (EXPO_PUBLIC_ prefix required)
// Restart the dev server after changing .env values

export const ENV = {
    API_BASE_URL: process.env.EXPO_PUBLIC_API_URL || 'https://filmy-backend.onrender.com/api/v1',
    DEV_AUTH_TOKEN: process.env.EXPO_PUBLIC_DEV_TOKEN || "eyJhbGciOiJIUzI1NiIsImtpZCI6IldadEJnODcycFR6dElDcXAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2lkYnh0aHluaXNnd2dua2Rza2dhLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI0NTJjMmI0Yy00OTNkLTRmYzItODgxMy0yNWEwMjZjODk3NDciLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY3MTQ2NDk1LCJpYXQiOjE3NjY1NDE2OTUsImVtYWlsIjoiIiwicGhvbmUiOiI5MTkxODI3MjA1OTMiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJwaG9uZSIsInByb3ZpZGVycyI6WyJwaG9uZSJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNDUyYzJiNGMtNDkzZC00ZmMyLTg4MTMtMjVhMDI2Yzg5NzQ3In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib3RwIiwidGltZXN0YW1wIjoxNzY2NTQxNjk1fV0sInNlc3Npb25faWQiOiIzMTU1NjQ2Yy0yNWE4LTQ4ODItOWVhNS04ZDY0MmU1ZGQyMmQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.MP2_aeY7rSNue-AE7MPSqacJUNfbltm_VZQuLOXxe5Q",
    IS_DEV: __DEV__,
} as const;
